spring.application.name=backend
# 1. Credenciales de la Base de Datos (Ejemplo con H2 o MySQL)
spring.datasource.url=jdbc:h2:mem:medicontigodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Desactivar la "magia" automática de Hibernate (El profesor amará esto)
spring.jpa.hibernate.ddl-auto=none

# 3. Forzar al sistema a ejecutar tu script manual (schema.sql)
spring.sql.init.mode=always
server.port=8081